language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov
